In [32]:
import pandas as pd
import numpy as np
df = pd.read_csv('student_performance1.csv')
df.head()

,math score,reading score,writing score,placement score,club join year,placement offer count
0,11,33,24,34,2018,3
1,27,55,41,8,2020,3
2,32,13,20,10,2020,2
3,73,80,74,82,2020,2
4,70,77,60,77,2020,2

In [33]:
df.mean()

math score                 84.758621
reading score             111.413793
writing score              85.551724
placement score           105.965517
club join year           2020.000000
placement offer count       2.517241
dtype: float64

In [35]:
df.loc[:, 'math score'].mean()

84.75862068965517

In [36]:
df.mean(axis=1)[0:4]

0    353.833333
1    359.000000
2    349.500000
3    388.500000
dtype: float64

In [37]:
df.median()

math score                 70.0
reading score              81.0
writing score              72.0
placement score            86.0
club join year           2020.0
placement offer count       3.0
dtype: float64

In [38]:
df.median(axis=1)[0:4]

0    28.5
1    34.0
2    16.5
3    77.0
dtype: float64

In [39]:
df.mode()

,math score,reading score,writing score,placement score,club join year,placement offer count
0,72,75,74.0,86.0,2020.0,3.0
1,74,77,NaN,NaN,NaN,NaN

In [40]:
df.loc[:,'math score'].mode()

0    72
1    74
Name: math score, dtype: int64

In [41]:
df.min()

math score                 11
reading score              13
writing score              20
placement score             8
club join year           2018
placement offer count       1
dtype: int64

In [42]:
df.loc[:,'math score'].min(skipna = False)

11

In [43]:
df.max()

math score                433
reading score             500
writing score             344
placement score           459
club join year           2022
placement offer count       3
dtype: int64

In [44]:
df.loc[:,'math score'].max(skipna = False)

433

In [45]:
df.std()

math score                77.069382
reading score            104.799304
writing score             67.935677
placement score           93.316084
club join year             1.362770
placement offer count      0.687682
dtype: float64

In [46]:
df.loc[:,'reading score'].std()

104.79930385584608

In [47]:
df.std(axis=1)[0:4]

0    815.363334
1    813.956018
2    818.436986
3    799.842422
dtype: float64

In [48]:
df.groupby(['club join year'])['placement score'].mean()

club join year
2018     77.400000
2019     83.400000
2020    120.800000
2021     82.333333
2022    135.666667
Name: placement score, dtype: float64

In [50]:
df.groupby(['reading score'])['placement offer count'].mean()

reading score
13     2.0
33     3.0
55     3.0
75     2.5
77     2.0
79     2.0
80     2.0
81     3.0
85     1.0
87     3.0
88     3.0
91     3.0
92     3.0
93     3.0
94     2.0
95     3.0
300    3.0
400    3.0
500    3.0
Name: placement offer count, dtype: float64

In [51]:
from sklearn import preprocessing
enc = preprocessing.OneHotEncoder()
enc_df = pd.DataFrame(enc.fit_transform(df[['reading score']]).toarray())
enc_df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [52]:
df_encode =df.join(enc_df)
df_encode.head()

,math score,reading score,writing score,placement score,club join year,placement offer count,0,1,2,3,...,9,10,11,12,13,14,15,16,17,18
0,11,33,24,34,2018,3,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,27,55,41,8,2020,3,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,32,13,20,10,2020,2,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,73,80,74,82,2020,2,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,70,77,60,77,2020,2,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [53]:
csv_url = pd.read_csv('iris.csv')

In [55]:
#iris = pd.read_csv(csv_url, names = col_names)
irisSet = (csv_url['species']=='setosa')

In [56]:
print(irisSet)

0       True
1       True
2       True
3       True
4       True
       ...
145    False
146    False
147    False
148    False
149    False
Name: species, Length: 150, dtype: bool

In [57]:
print(csv_url[irisSet].describe())

       sepal_length  sepal_width  petal_length  petal_width
count      50.00000    50.000000     50.000000     50.00000
mean        5.00600     3.418000      1.464000      0.24400
std         0.35249     0.381024      0.173511      0.10721
min         4.30000     2.300000      1.000000      0.10000
25%         4.80000     3.125000      1.400000      0.20000
50%         5.00000     3.400000      1.500000      0.20000
75%         5.20000     3.675000      1.575000      0.30000
max         5.80000     4.400000      1.900000      0.60000

In [58]:
irisVer = (csv_url['species']== 'versicolor')

In [59]:
print(csv_url[irisVer].describe())

       sepal_length  sepal_width  petal_length  petal_width
count     50.000000    50.000000     50.000000    50.000000
mean       5.936000     2.770000      4.260000     1.326000
std        0.516171     0.313798      0.469911     0.197753
min        4.900000     2.000000      3.000000     1.000000
25%        5.600000     2.525000      4.000000     1.200000
50%        5.900000     2.800000      4.350000     1.300000
75%        6.300000     3.000000      4.600000     1.500000
max        7.000000     3.400000      5.100000     1.800000

In [60]:
irisVir = (csv_url['species']=='virginica')

In [61]:
print(csv_url[irisVir].describe())

       sepal_length  sepal_width  petal_length  petal_width
count      50.00000    50.000000     50.000000     50.00000
mean        6.58800     2.974000      5.552000      2.02600
std         0.63588     0.322497      0.551895      0.27465
min         4.90000     2.200000      4.500000      1.40000
25%         6.22500     2.800000      5.100000      1.80000
50%         6.50000     3.000000      5.550000      2.00000
75%         6.90000     3.175000      5.875000      2.30000
max         7.90000     3.800000      6.900000      2.50000